sudo: required
services:
  - docker

before-install:
  - docker build -t gummie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gummie/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-780704099841"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
  secure: "$AWS_SECURE_KEY"
